FROM eclipse-temurin:17.0.8_7-jdk
# 인자 설정
ARG JAR_FILE=build/libs/*.jar
# jar 파일 복제
COPY ${JAR_FILE} discovery-server.jar

# todo ENTRYPOINT ["java","-Dspring.profiles.active=dev","-jar","/discovery-server.jar"] 프로파일 변경 해야함. #
# 실행 명령어
ENTRYPOINT ["java", "-jar","-Dspring.profiles.active=dev", "discovery-server.jar"]