name: Movement-Service CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Movement-Service/**'

env:
  SERVICE_NAME: ${{ secrets.MOVEMENT_SERVICE }}

jobs:
  build:
    name: Build MicroService
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Gradle Caching 
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          Movement-Service/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('Movement-Service/gradle/wrapper/gradle-wrapper.properties', 'Movement-Service/build.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x ./${{ env.SERVICE_NAME }}/gradlew

    - name: Build ${{ env.SERVICE_NAME }}
      run: |
        cd ./${{ env.SERVICE_NAME }}
        ./gradlew clean build -x test

    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker build & push
      run: |
        cd ${{ env.SERVICE_NAME }}
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 \
          -f Dockerfile-dev \
          -t ${{ secrets.DOCKER_USER_NAME }}/gachon-movement-service:${{ secrets.DOCKER_TAG }} \
          --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "Deploy 쉘 스크립트 실행"
            sudo ./deploy.sh
