name: User Service CI

on:
  push:
    branches: [ main ]
    paths:
      - 'User-Service/**'

jobs:
  build-and-deploy:
    name: Build User Service
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Gradle 캐시 설정 추가
    - name: Gradle Caching 
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          User-Service/.gradle  # 프로젝트별 Gradle 캐시 디렉토리
        key: ${{ runner.os }}-gradle-${{ hashFiles('User-Service/gradle/wrapper/gradle-wrapper.properties', 'User-Service/build.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Gradle Build를 위한 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x ./User-Service/gradlew

    - name: Build User Service
      run: |
        cd ./User-Service
        ./gradlew clean build -x test

    # DockerHub 로그인
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker build & push
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -f ./User-Service/Dockerfile-dev -t ${{ secrets.DOCKER_USER_NAME }}/gachonlife:${{ secrets.DOCKER_TAG }} --push .
