server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: # Discovery-Service Docker Container Name
      defaultZone: http://${DISCOVERY_SERVICE}:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
#              - "http://localhost:3000"
#              - "http://127.0.0.1:5500"
#            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - Authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - OPTIONS
              - DELETE
            exposedHeaders:
              - "Authorization"
              - "X-AUTH-TOKEN"
      routes:
        # ============== USER-SERVICE =============
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthenticationFilter
        # ============== BUILDING-SERVICE =============
        - id: building-service
          uri: lb://BUILDING-SERVICE
          predicates:
            - Path=/building-service/**
          filters:
            - RewritePath=/building-service/(?<segment>.*), /$\{segment}
        # ============== MOVEMENT-SERVICE =============
        - id: movement-service
          uri: lb://MOVEMENT-SERVICE
          predicates:
            - Path=/movement-service/**
          filters:
            - RewritePath=/movement-service/(?<segment>.*), /$\{segment}
            - AuthenticationFilter